#line_length:
#  warning: 120
#  ignores_function_declarations: true
#  ignores_comments: true
#  ignores_interpolated_strings: true
#  ignores_urls: true
#
#disabled_rules: # rule identifiers to exclude from running
#- trailing_whitespace
#- identifier_name
#- line_length
#
#excluded: # paths to ignore during linting. Takes precedence over `included`.
#  - Carthage
#  - Pods
#
